CREATE DATABASE BDAppPasteleria;
USE BDAppPasteleria;

CREATE TABLE tb_Persona(
Id INT PRIMARY KEY AUTO_INCREMENT,
IdUsuario INT,
Nombre VARCHAR(60) NOT NULL,
Apellidos VARCHAR(60) NOT NULL,
FechaNac DATE,
Edad INT,
Genero CHAR(1),
Correo VARCHAR(50) NOT NULL,
FOREIGN KEY (IdUsuario) REFERENCES tb_Usuario(Id)
);

CREATE TABLE tb_Usuario(
Id INT PRIMARY KEY AUTO_INCREMENT,
Usuario VARCHAR(40) NOT NULL,
Clave VARCHAR(40) NOT NULL
);

