CREATE DATABASE BDAppPasteleria;
USE BDAppPasteleria;

CREATE TABLE tb_Persona(
Id INT PRIMARY KEY AUTO_INCREMENT,
Nombre VARCHAR(60) NOT NULL,
Apellidos VARCHAR(60) NOT NULL,
FechaNac DATE,
Edad INT,
Genero CHAR(1),
Correo VARCHAR(50) NOT NULL
);

CREATE TABLE tb_Usuario(
Id INT PRIMARY KEY AUTO_INCREMENT,
IdPersona INT,
Usuario VARCHAR(40) NOT NULL,
Clave VARCHAR(40) NOT NULL,
FOREIGN KEY (IdPersona) REFERENCES tb_Persona(Id)
);

